package co.insou.refer.gui.page;

/**
 * Created by insou on 30/01/2016.
 */
public enum GUIPageType {

    MAIN_MENU,

    REFER_MENU,
    REFER_ONLINE,
    REFER_CONFIRM,

    REQUEST_CONFIRM,
    REQUEST_SELECT,

    HISTORY,

    TUTORIAL,
    REFER_HELP,
    HISTORY_HELP,
    POINTS_HELP,
    REQUEST_HELP,

    ADMIN_MENU,

    CLOSE_PAGE,
    PLAYER_MANAGEMENT, SERVER_HISTORY, REWARDS, PLAYER_MANAGEMENT_SELECT, PLAYER_MANAGEMENT_SELECT_ONLINE, PLAYER_MANAGEMENT_SELECT_OFFLINE, PLAYER_MANAGEMENT_HISTORY, PLAYER_MANAGEMENT_SELECT_OFFLINE_CONFIRM, CLOSE_GUI
}
